CREATE DATABASE DB_BLOG
GO

USE DB_BLOG
GO

/* TABLA USUARIOS*/
CREATE TABLE T_USERS(
COD_USER INT IDENTITY(1,1),
PERFIL VARCHAR(5),
SESSION CHAR(1)
)
GO

/* TABLA PERFILES*/
CREATE TABLE T_PERFIL(
COD_PERFIL INT IDENTITY(1,1),
COD_USER INT,
--COD_PRODUCTO INT,
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(30),
FECHA_NACIMIENTO DATETIME,
EMAIL VARCHAR(50),
CIUDAD VARCHAR(20),
FECHA_INI_SESSION DATETIME
)
GO

/* TABLA CATEGORIAS*/
CREATE TABLE T_CATEGORIA(
COD_CAT INT IDENTITY(1,1),
DESCRIPCION VARCHAR(20),
)
GO

/* TABLA ADMINISTRADOR*/
CREATE TABLE T_ADMIN(
COD_ADMIN INT IDENTITY(1,1),
COD_USER INT,
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(30),
FECHA_INI_SESSION DATETIME,
EMAIL VARCHAR(50)
)
GO

/* TABLA PRODUCTOS*/
CREATE TABLE T_PRODUCTO(
COD_PRODUCTO INT IDENTITY(1,1),
COD_CAT INT,
NOM_PROD VARCHAR(80),
DESCRIPCION VARCHAR(50),
PRECIO DECIMAL(18,2),
STOCK INT
)
GO
----------------------------------------------------------------------------------------------
/* PRIMARY KEYS*/
ALTER TABLE T_USERS ADD CONSTRAINT PK_USERS PRIMARY KEY(COD_USER)
GO
ALTER TABLE T_PERFIL ADD CONSTRAINT PK_PERFIL PRIMARY KEY(COD_PERFIL)
GO
ALTER TABLE T_CATEGORIA ADD CONSTRAINT PK_CAT PRIMARY KEY(COD_CAT)
GO
ALTER TABLE T_ADMIN ADD CONSTRAINT PK_ADMIN PRIMARY KEY (COD_ADMIN)
GO
ALTER TABLE T_PRODUCTO ADD CONSTRAINT PK_PROD PRIMARY KEY(COD_PRODUCTO)
GO

------------------------------------------------------------------------------------------------

/* FOREIGN KEYS */
ALTER TABLE T_PERFIL ADD CONSTRAINT FK_PERFIL FOREIGN KEY (COD_USER) REFERENCES T_USERS(COD_USER)
GO

ALTER TABLE T_ADMIN ADD CONSTRAINT FK_ADMIN FOREIGN KEY (COD_USER) REFERENCES T_USERS(COD_USER)
GO

ALTER TABLE T_PRODUCTO ADD CONSTRAINT FK_CAT FOREIGN KEY (COD_CAT) REFERENCES T_CATEGORIA(COD_CAT)
GO

--ALTER TABLE T_PERFIL ADD CONSTRAINT FK_PRODUCT FOREIGN KEY (COD_PRODUCTO) REFERENCES T_PRODUCTO(COD_PRODUCTO)
--GO

-------------------------------------------------------------------------------------------------------

/* INSERTANDO CATEGORIAS*/
INSERT INTO T_CATEGORIA VALUES ('LAPTOP')
INSERT INTO T_CATEGORIA VALUES ('TABLET')
INSERT INTO T_CATEGORIA VALUES ('ACCESORIOS')

SELECT * FROM T_CATEGORIA

/* INSERTANDO PRODUCTO*/
INSERT INTO T_PRODUCTO VALUES(1,'HP CORE 2 DUO','COMPUTADORA HP A BAJO PRECIO',1200,4)
INSERT INTO T_PRODUCTO VALUES(2,'MAC OS TABLET','TABLET MARCA MAC APPLE',1100,2)
INSERT INTO T_PRODUCTO VALUES(2,'BLACK BERRY TABLER','TABLET PLAYBOOK',1000,4)
INSERT INTO T_PRODUCTO VALUES(3,'CAMARA WEB','CAMARA WEB DE 2 MEGAPIXELES HP',500,6)

SELECT * FROM T_PRODUCTO

/* INSERTANDO PERFIL*/
INSERT INTO T_PERFIL VALUES (1,'JUAN','PEREZ','10/10/10','TELLO_12@HOTMAIL.COM','LIMA','10/10/10')
INSERT INTO T_PERFIL VALUES (1,'CARLOS','SANDALINIA','10/10/10','CARLOS@HOTMAIL.COM','LIMA','10/10/10')

SELECT * FROM T_PERFIL

/* INSERTANDO T_ADMIN*/
INSERT INTO T_ADMIN VALUES (2,'MIGUEL','GARCIA','10/10/10','MIGUEL@HOTMAIL.COM')

SELECT * FROM T_ADMIN

/* INSERTANDO T_USERS*/
INSERT INTO T_USERS VALUES ('ADMIN','0')
INSERT INTO T_USERS VALUES ('USER','0')

SELECT * FROM T_USERS


/* PROCEDIMIENTOS ALMACENADOS */

	-- INSERTANDO CATEGORIAS
CREATE PROCEDURE INS_TCATEGORIA
	@DES VARCHAR(20)
AS
	INSERT INTO T_CATEGORIA VALUES (@DES)
GO

EXEC INS_TCATEGORIA 'ANDROIDS'

	-- INSERTANDO PRODUCTOS
CREATE PROCEDURE INS_TPRODUCTO
	@CODCAT INT,
	@NOM VARCHAR(20),
	@DESC VARCHAR(50),
	@PRECIO DECIMAL(18,2),
	@STOCK INT
AS
	INSERT INTO T_PRODUCTO VALUES (@CODCAT,@NOM,@DESC,@PRECIO,@STOCK)
GO

EXEC INS_TPRODUCTO 1,'COMPUTADORA 2 MAC OS','COMPUTADORES MAC',1200,4

	-- INSERTANDO PERFILES
CREATE PROCEDURE INS_TPERFIL
	@CODUSER INT,
	@NOM VARCHAR(20),
	@APE VARCHAR(30),
	@FNAC DATETIME,
	@EMAIL VARCHAR(50),
	@CIU VARCHAR(20),
	@SESSION DATETIME
AS
	INSERT INTO T_PERFIL VALUES (@CODUSER,@NOM,@APE,@FNAC,@EMAIL,@CIU,@SESSION)
GO

EXEC INS_TPERFIL 2,'SANDRA','CRISTINIANA','10/04/03','SANDRA@HOTMAIL.COM','CALLAO','05/11/08'


/*-----------------------------------------------*/
-- Listar categorias
CREATE PROCEDURE SPL_CATEGORIA
@COD int
AS
SELECT DESCRIPCION FROM T_CATEGORIA ORDER BY 2
GO

EXEC SPL_CATEGORIA 0

-- LISTAR PRODUCTOS
CREATE PROCEDURE SPL_PRODUCTO
@CODPROD INT
AS
SELECT P.COD_PRODUCTO 'CODIGO', C.DESCRIPCION 'CATEGORIA', P.NOM_PROD 'NOMBRE', 
P.DESCRIPCION, P.PRECIO, P.STOCK FROM T_PRODUCTO P, T_CATEGORIA C 
WHERE P.COD_CAT = C.COD_CAT ORDER BY P.COD_PRODUCTO DESC
GO

EXEC SPL_PRODUCTO 0

-- LISTAR PERFILES USUARIOS
CREATE PROCEDURE SPL_PERFIL
@COD INT
AS
SELECT U.PERFIL,P.NOMBRE,P.APELLIDO,P.FECHA_NACIMIENTO 'FECHA NACIMIENTO',P.EMAIL,P.CIUDAD,P.FECHA_INI_SESSION 'ULTIMA SESSION'
FROM dbo.T_PERFIL P , dbo.T_USERS U
WHERE P.COD_USER = U.COD_USER ORDER BY P.NOMBRE 
GO

EXEC SPL_PERFIL 0

ALTER TABLE T_PRODUCTO ADD IMAGEN VARCHAR(50)
ALTER TABLE T_USERS ADD PASSWORD VARCHAR(10)

-- CREANDO INICIO DE SESSION
CREATE PROCEDURE SPL_LOGIN
@US VARCHAR(50)
AS
BEGIN TRY
	IF EXISTS(SELECT * FROM T_USERS WHERE PERFIL = 'USER' AND PERFIL = @US)
		BEGIN
			SELECT * FROM T_PERFIL WHERE COD_USER=2
			PRINT 'USUARIO'
		END
	ELSE 
		BEGIN
			SELECT * FROM T_ADMIN WHERE COD_USER=1
			PRINT 'ADMINISTRADOR'
		END

END TRY
BEGIN CATCH
ROLLBACK TRANSACTION
SELECT  ERROR_MESSAGE()
SELECT ERROR_PROCEDURE()
END CATCH
GO

EXEC SPL_LOGIN 'ADMIN'